### ISSUE TITLE
Ошибка Login Password not found

### ISSUE THREAD

**Issue by bismoney** [getdrive/Lazy-RDP#11]
Привет, все перепроверил 100 раз, везде все верно, но после ввода всего получаю:

cat: /home/Lazy-RDP/result: No such file or directory
                                      +-----------------------------+
                                      | Login/Password not found :( |
                                      +-----------------------------+

Press [ENTER] to return to the Main menu 

Создаю /home/Lazy-RDP/result, он ее удаляет и опять пишет что ее нет :)
Пути указывал к login/pass по разному и как в видео и по своему и просто manual вводил логин и пароль, всегда эта ошибка в итоге.

Не подскажешь что делаю не так? Реально все уже перепроверил, просто так бы не писал :)

**Comment by getdrive** [comment]
> 
> 
> Привет, все перепроверил 100 раз, везде все верно, но после ввода всего получаю:
> 
> cat: /home/Lazy-RDP/result: No such file or directory
> +-----------------------------+
> | Login/Password not found :( |
> +-----------------------------+
> 
> Press [ENTER] to return to the Main menu
> 
> Создаю /home/Lazy-RDP/result, он ее удаляет и опять пишет что ее нет :)
> Пути указывал к login/pass по разному и как в видео и по своему и просто manual вводил логин и пароль, всегда эта ошибка в итоге.
> 
> Не подскажешь что делаю не так? Реально все уже перепроверил, просто так бы не писал :)

Приветствую. Скажи, какая версия hydra установлена?
