### ISSUE TITLE
Нужна помощь 

### ISSUE THREAD

**Issue by Maloyone228** [getdrive/Lazy-RDP#12]
Постоянно пишет при сканировании из файла что файл не найден, формат просто айпи, формат файла txt, менял расположения все верно при обычном сканировании и бруте на 1 айпи все работает отлично, при попытке просканировать несколько айпи пишет не найден файл

**Comment by getdrive** [comment]
Проверяйте, какой путь вводите до файла с IP-адресами..

![1](https://user-images.githubusercontent.com/20697688/133401652-102da35c-458f-46b2-bb50-f926557dae9f.jpg)
![2](https://user-images.githubusercontent.com/20697688/133401670-e147cd09-408d-4bf5-810e-742d22045d37.jpg)
![3](https://user-images.githubusercontent.com/20697688/133401690-3317b712-6122-46c0-82b0-bc10cef73360.jpg)

у меня работает корректно.
