### ISSUE TITLE
выдает ложные гуды

### ISSUE THREAD

**Issue by Maloyone228** [getdrive/Lazy-RDP#13]
начал брут через потатор так как пробовал гидрой не дал результатов положительных в списоке были рабочии, потатор после 5 часво работы выдал просто весь список провереных паролей в тхт гуд

**Comment by Maloyone228** [comment]
[good.txt](https://github.com/getdrive/Lazy-RDP/files/6988866/good.txt)

**Comment by Maloyone228** [comment]
![image](https://user-images.githubusercontent.com/54377512/129492252-da828ba3-6308-4d42-ac28-a657a6676420.png)

**Comment by Maloyone228** [comment]
дает ложные гуды
настоящего пароля нет в списке

**Comment by getdrive** [comment]
Это на смотреть по конкретному IP-адресу со скриншота, коды возврата в логе patator  и их длину..
Вот примерно так будет выглядеть команда: 

python patator.py rdp_login host=FILE0 port=ПОРТ_RDP user=FILE1  password=FILE2  0=ФАЙЛ_С_IP_АДРЕСОМ 1=ФАЙЛ _С_ЛОГИНАМИ 2=ФАЙЛ_С_ПАРОЛЯМИ -t 120 --max-retries=0 -x ignore:code=1 -x ignore:code=-11 -x ignore:fgrep='FAIL',size=500-700

**Comment by getdrive** [comment]
Также повторюсь, все проверки с использованием скрипта Lazy-RDP, можно проводить только на своих сетях или с письменного разрешения владельцев хостов. 
Удачи ;-)
