### ISSUE TITLE
cat: /root/Lazy-RDP-v.1.30/Results/RUNTIME.log: Datei oder Verzeichnis nicht gefunden (File or Folder not found)

### ISSUE THREAD

**Issue by mmuncan1980** [getdrive/Lazy-RDP#14]
Hello!
If i try to bruteforce i always get this message.

when i manually do mkdir Results and scan manually it always gets deleted when trying to bruteforce. 

Please help. 

:)

**Comment by getdrive** [comment]
Hi. Need details. How do you run the script? Did you run the INSTALL.sh file beforehand? What was the order in which the options were selected? In which option does the error appear?
Runtime.log is created during pator bruteforcing. Perhaps the file is not created due to some restrictions.

**Comment by getdrive** [comment]
I found a mistake. Fixed
