### ISSUE TITLE
Ошибка установки пакета freerdp

### ISSUE THREAD

**Issue by Zem0rt** [getdrive/Lazy-RDP#15]
У меня проблема с установкой  freerdp2-x11 (freerdp2-dev) Пишет "E: Не удалось найти пакет"
OS: Kali linux 2.0 (GNOME Ver:3.14.1) 64 bit и 32 bit 
На виртуальной машине *VMware Workstation Pro 16*
Скачал Kali linux здесь: http://old.kali.org/kali-images/kali-2.0/ [kali-linux-2.0-amd64.iso и kali-linux-2.0-i386.ico]
Ошибка:
![93Qa0PGM](https://user-images.githubusercontent.com/99068726/152652119-a9d86db9-4a09-4cbd-84d7-22847b10d042.png)

**Comment by getdrive** [comment]
что там в  выводе  cat /etc/apt/sources.list

**Comment by Zem0rt** [comment]
> Привет. Покажи что там в выводе: cat /etc/apt/sources.list и cat /etc/*-release
> 
> P.S. есть подозрение, что используется дистрибутив SANA. В том репозитории нет пакетов freerdp2. Новая hydra не правильно скомпилируется без них. Да и patator без freerdp2-x11 тоже не будет работать. Вывод: обновить kali, либо добавить _НА СВОЙ СТРАХ И РИСК_ репозиторий в /etc/apt/sources.list.d/ файл c каким -нибудь названием kali_rolling.list Вписать в него строку: deb http://http.kali.org/kali kali-rolling main contrib non-free После этого можно будет установить freerdp2: sudo apt update -y; sudo apt install freerdp2-dev freerdp2-x11 -y
> 
> НО БУДЬТЕ ОСТОРОЖНЫ !!! ЕСЛИ ВЫ ДОБАВИТЕ строку в sources.list и СДЕЛАЕТЕ sudo apt upgrade, ПАКЕТЫ ИЗ kali-rolling могут убить вашу SANA.

Привет.
![Снимок экрана из 2022-02-06 12:22:34](https://user-images.githubusercontent.com/99068726/152676532-ea03ee80-3f84-4476-95c9-b51359e21d41.png)

**Comment by getdrive** [comment]
Ну понятно. Дистрибутив SANA.
Тогда по инструкции выше. Либо обновление kali linux, либо добавляйте дополнительный репозиторий:
> echo "deb http://http.kali.org/kali kali-rolling main contrib non-free" > /etc/apt/sources.list.d/kali_rolling.list
> sudo apt update -y; sudo apt install freerdp2-dev freerdp2-x11 -y

**Comment by Zem0rt** [comment]
> Ну понятно. Дистрибутив SANA. Тогда по инструкции выше. Либо обновление kali linux, либо добавляйте дополнительный репозиторий:
> 
> > echo "deb http://http.kali.org/kali kali-rolling main contrib non-free" > /etc/apt/sources.list.d/kali_rolling.list
> > sudo apt update -y; sudo apt install freerdp2-dev freerdp2-x11 -y
 
Ok. Я попробую сперва parrot os если получится то буду юзать parrot и хотел спросить какую версию beta или 4.11.3.

**Comment by getdrive** [comment]
> > Ну понятно. Дистрибутив SANA. Тогда по инструкции выше. Либо обновление kali linux, либо добавляйте дополнительный репозиторий:
> > > echo "deb http://http.kali.org/kali kali-rolling main contrib non-free" > /etc/apt/sources.list.d/kali_rolling.list
> > > sudo apt update -y; sudo apt install freerdp2-dev freerdp2-x11 -y
> 
> Ok. Я попробую сперва parrot os если получится то буду юзать parrot и хотел спросить какую версию beta или 4.11.3.

Лучше stable, security edition. В бете могут быть неисправленные ошибки.
