### ISSUE TITLE
Error when i try to bruteforce [open3389: file or folder not found]

### ISSUE THREAD

**Issue by mmuncan1980** [getdrive/Lazy-RDP#16]
Menu chosen was first 3.) then 4.) then 1.) Hydra 9.3
then comes

cat: /home/XXX/Downloads/Lazy-RDP/open3389: file or folder not found
                                       +---------------------------+
                                       | Логин/Пароль не найден :( |
                                       +---------------------------+

Нажмите [ENTER] для перехода в Главное меню

**Comment by getdrive** [comment]
> 

The first thing to do is to scan the host/hosts for an open RDP port (Menu option 1 or option 2). After that you need to run the bruteforce - option 3
