### ISSUE TITLE
dont started

### ISSUE THREAD

**Issue by dnkls** [getdrive/Lazy-RDP#2]
I start it ./start but only check update and nothing else , how start it?

**Comment by getdrive** [comment]
It looks like the problem is with the delay in response from ifconfig.te
Fixed start script
The communication check is now conducted with ident.me. Check update v.1.21

**Comment by getdrive** [comment]
@dnkls 
It looks like the problem's with the delay in response from ifconfig.me
Fixed start script
The link check's now conducted with ident.me. Check update v.1.21!

**Comment by dnkls** [comment]
Koroche bro sorry za translit russkoi klaviaturi net , no skript imenno **na servere** ne zapuskaetsya. 
>Na kompe norm rabotaet.

Pokoviryal i zametil chto **na servere** zapuskaetsya kogda vse faili v odnoi papke .

**Comment by dnkls** [comment]
Potom eshe takaya oshibka pri vibore scana po stranam 

https://i.imgur.com/TuWWsmP.png
