### ISSUE TITLE
Скорость падает (

### ISSUE THREAD

**Issue by dnkls** [getdrive/Lazy-RDP#5]
По любому скорость перебора падает до 1 r/s , сам выстоял рейти и потоки по разному , тупо падает скорость после десяти минут примерно 

```
11:10:23 patator    INFO - Starting Patator v0.7-beta (https://github.com/lanjelot/patator) at 2017-11-15 11:10 UTC
11:10:24 patator    INFO -
11:10:24 patator    INFO - code  size    time | candidate                          |   num | mesg
11:10:24 patator    INFO - -----------------------------------------------------------------------------

11:10:27 patator    INFO - Progress:   0% (80/1611554295) | Speed: 73 r/s | ETC: 16:31:36 (6125:21:09 remaining)

11:10:32 patator    INFO - Progress:   0% (379/1611554295) | Speed: 66 r/s | ETC: 14:42:34 (6747:32:01 remaining)

11:10:37 patator    INFO - Progress:   0% (530/1611554295) | Speed: 63 r/s | ETC: 17:00:53 (7085:50:15 remaining)

11:11:14 patator    INFO - Progress:   0% (2184/1611554295) | Speed: 44 r/s | ETC: 20:28:18 (10065:17:04 remaining)

11:11:39 patator    INFO - Progress:   0% (3324/1611554295) | Speed: 45 r/s | ETC: 12:56:05 (9937:44:26 remaining)

11:11:51 patator    INFO - Progress:   0% (3848/1611554295) | Speed: 45 r/s | ETC: 17:34:28 (9894:22:36 remaining)

11:12:23 patator    INFO - Progress:   0% (5314/1611554295) | Speed: 47 r/s | ETC: 13:44:46 (9602:32:23 remaining)

11:12:40 patator    INFO - Progress:   0% (6150/1611554295) | Speed: 47 r/s | ETC: 16:29:07 (9557:16:27 remaining)

11:45:56 patator    INFO - Progress:   0% (93916/1611554295) | Speed: 39 r/s | ETC: 05:58:35 (11538:12:38 remaining)

11:45:58 patator    INFO - Progress:   0% (93991/1611554295) | Speed: 39 r/s | ETC: 06:01:17 (11490:15:19 remaining)

11:46:06 patator    INFO - Progress:   0% (94372/1611554295) | Speed: 40 r/s | ETC: 11:49:32 (11088:03:26 remaining)

11:46:31 patator    INFO - Progress:   0% (95522/1611554295) | Speed: 45 r/s | ETC: 03:56:26 (9904:09:55 remaining)

11:59:12 patator    INFO - Progress:   0% (126395/1611554295) | Speed: 43 r/s | ETC: 18:20:11 (10494:20:59 remaining)

12:02:12 patator    INFO - Progress:   0% (133822/1611554295) | Speed: 42 r/s | ETC: 14:30:01 (10706:27:49 remaining)

12:04:49 patator    INFO - Progress:   0% (139466/1611554295) | Speed: 43 r/s | ETC: 10:43:06 (10414:38:17 remaining)

12:05:10 patator    INFO - Progress:   0% (139491/1611554295) | Speed: 43 r/s | ETC: 16:24:48 (10372:19:38 remaining)

12:12:26 patator    INFO - Progress:   0% (139891/1611554295) | Speed: 4 r/s | ETC: 19:38:56 (101863:26:30 remaining)

12:12:40 patator    INFO - Progress:   0% (139896/1611554295) | Speed: 4 r/s | ETC: 19:36:00 (101863:23:19 remaining)

12:14:52 patator    INFO - Progress:   0% (140016/1611554295) | Speed: 3 r/s | ETC: 11:19:53 (132311:05:00 remaining)

12:28:16 patator    INFO - Progress:   0% (140570/1611554295) | Speed: 1 r/s | ETC: 05:29:50 (321185:01:34 remaining)

12:36:15 patator    INFO - Progress:   0% (140858/1611554295) | Speed: 1 r/s | ETC: 22:52:13 (439690:15:58 remaining)

12:40:36 patator    INFO - Progress:   0% (141008/1611554295) | Speed: 1 r/s | ETC: 03:02:50 (501446:22:13 remaining)

12:43:43 patator    INFO - Progress:   0% (141112/1611554295) | Speed: 1 r/s | ETC: 11:12:29 (544246:28:46 remaining)

13:09:26 patator    INFO - Progress:   0% (141983/1611554295) | Speed: 1 r/s | ETC: 16:35:05 (781035:25:39 remaining)

13:11:34 patator    INFO - Progress:   0% (142058/1611554295) | Speed: 1 r/s | ETC: 16:35:54 (781443:24:19 remaining)

```

**Comment by dnkls** [comment]
`*To refresh INFO-Progress press [ENTER]=>
*Pause/Unpause [P]=>[ENTER]=>

11:10:23 patator    INFO - Starting Patator v0.7-beta (https://github.com/lanjelot/patator) at 2017-11-15 11:10 UTC
11:10:24 patator    INFO -
11:10:24 patator    INFO - code  size    time | candidate                          |   num | mesg
11:10:24 patator    INFO - -----------------------------------------------------------------------------

11:10:27 patator    INFO - Progress:   0% (80/1611554295) | Speed: 73 r/s | ETC: 16:31:36 (6125:21:09 remaining)

11:10:32 patator    INFO - Progress:   0% (379/1611554295) | Speed: 66 r/s | ETC: 14:42:34 (6747:32:01 remaining)

11:10:37 patator    INFO - Progress:   0% (530/1611554295) | Speed: 63 r/s | ETC: 17:00:53 (7085:50:15 remaining)

11:11:14 patator    INFO - Progress:   0% (2184/1611554295) | Speed: 44 r/s | ETC: 20:28:18 (10065:17:04 remaining)

11:11:39 patator    INFO - Progress:   0% (3324/1611554295) | Speed: 45 r/s | ETC: 12:56:05 (9937:44:26 remaining)

11:11:51 patator    INFO - Progress:   0% (3848/1611554295) | Speed: 45 r/s | ETC: 17:34:28 (9894:22:36 remaining)

11:12:23 patator    INFO - Progress:   0% (5314/1611554295) | Speed: 47 r/s | ETC: 13:44:46 (9602:32:23 remaining)

11:12:40 patator    INFO - Progress:   0% (6150/1611554295) | Speed: 47 r/s | ETC: 16:29:07 (9557:16:27 remaining)

11:45:56 patator    INFO - Progress:   0% (93916/1611554295) | Speed: 39 r/s | ETC: 05:58:35 (11538:12:38 remaining)

11:45:58 patator    INFO - Progress:   0% (93991/1611554295) | Speed: 39 r/s | ETC: 06:01:17 (11490:15:19 remaining)

11:46:06 patator    INFO - Progress:   0% (94372/1611554295) | Speed: 40 r/s | ETC: 11:49:32 (11088:03:26 remaining)

11:46:31 patator    INFO - Progress:   0% (95522/1611554295) | Speed: 45 r/s | ETC: 03:56:26 (9904:09:55 remaining)

11:59:12 patator    INFO - Progress:   0% (126395/1611554295) | Speed: 43 r/s | ETC: 18:20:11 (10494:20:59 remaining)

12:02:12 patator    INFO - Progress:   0% (133822/1611554295) | Speed: 42 r/s | ETC: 14:30:01 (10706:27:49 remaining)

12:04:49 patator    INFO - Progress:   0% (139466/1611554295) | Speed: 43 r/s | ETC: 10:43:06 (10414:38:17 remaining)

12:05:10 patator    INFO - Progress:   0% (139491/1611554295) | Speed: 43 r/s | ETC: 16:24:48 (10372:19:38 remaining)

12:12:26 patator    INFO - Progress:   0% (139891/1611554295) | Speed: 4 r/s | ETC: 19:38:56 (101863:26:30 remaining)

12:12:40 patator    INFO - Progress:   0% (139896/1611554295) | Speed: 4 r/s | ETC: 19:36:00 (101863:23:19 remaining)

12:14:52 patator    INFO - Progress:   0% (140016/1611554295) | Speed: 3 r/s | ETC: 11:19:53 (132311:05:00 remaining)

12:28:16 patator    INFO - Progress:   0% (140570/1611554295) | Speed: 1 r/s | ETC: 05:29:50 (321185:01:34 remaining)

12:36:15 patator    INFO - Progress:   0% (140858/1611554295) | Speed: 1 r/s | ETC: 22:52:13 (439690:15:58 remaining)

12:40:36 patator    INFO - Progress:   0% (141008/1611554295) | Speed: 1 r/s | ETC: 03:02:50 (501446:22:13 remaining)

12:43:43 patator    INFO - Progress:   0% (141112/1611554295) | Speed: 1 r/s | ETC: 11:12:29 (544246:28:46 remaining)

13:09:26 patator    INFO - Progress:   0% (141983/1611554295) | Speed: 1 r/s | ETC: 16:35:05 (781035:25:39 remaining)

13:11:34 patator    INFO - Progress:   0% (142058/1611554295) | Speed: 1 r/s | ETC: 16:35:54 (781443:24:19 remaining)
`

**Comment by getdrive** [comment]
да, есть проблема.. с огромным количеством вариантов перебора, я пока хез, как переписать код пататора, чтобы обойти данный трабл.. Возможно что то на стороне атакуемого, IDS и прочая нечисть, заставляет так работать брут. Думаю, разбираюсь.. постепенно

**Comment by dnkls** [comment]
Бро все так же скорость падает ((( начинается перебор бодро но скорость таит на глазах, исправь плиз это как нибудь.

И еще момент, ты же понимаешь что брутят все на VPS зачем ты сделал Desktop XFCE и GNOME теперь через ./start не заводится. Приходится напрямую к rdp_brute.sh обращаться однако в этом случае он не находит директорию файлов юзеров или паролей для брута.

**Comment by sTiKyt** [comment]
Кстати также скорость падает и при использовании ncrack

**Comment by getdrive** [comment]
> ..ты же понимаешь что брутят все на VPS зачем ты сделал Desktop XFCE и GNOME теперь через ./start не заводится. Приходится напрямую к rdp_brute.sh обращаться однако в этом случае он не находит директорию файлов юзеров или паролей для брута.

Скрипт изначально делался для Kali Linux. В процессе разработки использовались два окружения рабочего стола: XFCE4 и Gnome. Поэтому был сделан start.sh, для предварительной проверки обновлений и необходимых, для работы скрипта, пакетов. Там же включена проверка запущенного окружения рабочего стола. Если вы используйте другой дистрибутив, то можете напрямую обратиться к rdp_brute.sh, но для корректной работы перебора, вам необходимо: либо поправить путь для запуска patator, либо скопировать  patator.py, в папку со скриптом rdp_brute. Так же при прямом запуске rdp_brute не будет работать "метод перебора по умолчанию" так как жестко прописан путь для списков с логинами и паролями, предполагающий запуск rdp_brute через start.sh. Все это легко находится и правится в коде руками. В данном git, алгоритм запуска скрипта меняться не будет. Если требуется использование сборки под конкретные нужды - welcome to open source! 
Так же можете попробовать более ранние релизы. Запуск rdp_brute.sh напрямую использовался до версии 1.16 включительно. Но естественно там нет исправлений, которые присутствуют в  последней версии.

Что касается падения скорости - то это прописано в алгоритме работы patator c rdp, делается расчет скорости соединения, ответов, количества  атакуемых адресов, количества попыток. Если упрощать  - чем меньше в процессе целей, тем меньше количество потоков.

Если скорость падает до нуля, требуется проанализировать лог сниффера.
Смоделировать такое падение скорости, в локальной сети, у меня не получилось.
