### ISSUE TITLE
Error on Default Checking

### ISSUE THREAD

**Issue by traictore** [getdrive/Lazy-RDP#7]
INFO][com.freerdp.client.common.cmdline] - loading channelEx cliprdr\n[17:39:19:217] [4177:4186] [INFO][com.freerdp.client.x11] - Authentication only. Don't connect to X.\n[17:39:33:809] [4177:4186] [ERROR][com.freerdp.core.transport] - BIO_read returned a system error 110: Connection timed out\n[17:39:33:809] [4177:4186] [ERROR][com.freerdp.core.nego] - Protocol Security Negotiation Failure\n[17:39:33:809] [4177:4186] [ERROR][com.freerdp.core] - freerdp_set_last_error ERRCONNECT_SECURITY_NEGO_CONNECT_FAILED [0x0002000C]\n[17:39:33:809] [4177:4186] [ERROR][com.freerdp.core.connection] - Error: protocol security negotiation or connection failure\n[17:39:33:809] [4177:4186] [ERROR][com.freerdp.core] - Authentication only, exit status 1

**Comment by getdrive** [comment]
fixed
