### ISSUE TITLE
Проблема с работой гидры.

### ISSUE THREAD

**Issue by QPM1Z** [getdrive/Lazy-RDP#8]
Здравствуй! 

Проблема при запуске брута через гидру. Указываю адрес к файлу с логинами/паролями для перебора, но сразу, при старте, гидра выдаёт следующую ошибку:
https://anonymousfiles.io/4rtGPtMD/

В чём может быть ошибка? 
Спасибо за внимание!

**Comment by getdrive** [comment]
Приветствую. Какая версия Lazy-RDP установлена? В скриншоте, на заднем фоне, не наблюдаю файла INSTALL. Он настраивает зависимости и компилирует новую гидру. Его нужно запустить в первую очередь.
